# Generated by Django 4.2.4 on 2023-08-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
        ('usuario', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumotrabajador',
            name='detalle_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.detalle_venta', verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='consumotrabajador',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='consumotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.trabajador', verbose_name='Nombre Trabajador'),
        ),
    ]
