# Generated by Django 4.1.7 on 2023-04-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='evento',
            name='id_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.compra', verbose_name='Fecha de Compra'),
            preserve_default=False,
        ),
    ]
