# Generated by Django 4.1.7 on 2023-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_compra_options_evento_id_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compra',
            options={'verbose_name_plural': 'detalles_compras'},
        ),
        migrations.AddField(
            model_name='compra',
            name='id_detalle_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.detalle_compra', verbose_name='Fecha detalle compra'),
            preserve_default=False,
        ),
    ]
