# Generated by Django 4.2.4 on 2023-08-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('inventario', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Nombre Producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_detalle_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.detalle_compra', verbose_name='Valor Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.proveedor', verbose_name='Nombre Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona'),
        ),
    ]
