# Generated by Django 4.2.4 on 2023-09-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_personalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default-producto.png', null=True, upload_to='productos/'),
        ),
    ]
