# Generated by Django 4.2.4 on 2023-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_personalizacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='precio',
            field=models.CharField(default=0, max_length=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
