# Generated by Django 4.2.4 on 2023-09-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_personalizacion_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='precio',
        ),
    ]
