# Generated by Django 4.2.4 on 2023-10-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_remove_personalizacion_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nombre_persona',
        ),
    ]
