# Generated by Django 4.2.4 on 2023-12-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_remove_compra_nombre_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_detalle_compra',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_compra',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado Evento'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.compra', verbose_name='compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='Fecha Compra'),
        ),
    ]
