# Generated by Django 4.1.7 on 2023-03-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.PositiveIntegerField(verbose_name='Documento:'),
        ),
    ]
