# Generated by Django 4.1.7 on 2023-04-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_persona_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_ingreso',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_salida',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Salida'),
        ),
    ]
