# Generated by Django 4.1.7 on 2023-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_turno_fecha_ingreso_alter_turno_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_ingreso',
            field=models.DateTimeField(help_text='HH/MM/SS', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_salida',
            field=models.DateTimeField(help_text='HH/MM/SS', verbose_name='Fecha de Salida'),
        ),
    ]
