# Generated by Django 4.1.7 on 2023-04-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_turno_fecha_ingreso_alter_turno_fecha_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador_Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.trabajador', verbose_name='trabajador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.turno', verbose_name='Turno')),
            ],
        ),
    ]
