# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_trabajador_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'Personas'},
        ),
        migrations.DeleteModel(
            name='Trabajador_Turno',
        ),
    ]
