# Generated by Django 4.2.4 on 2023-08-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='detalle_venta_cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_pago_total',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_persona',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago_total',
        ),
    ]
