# Generated by Django 4.2.4 on 2023-10-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_remove_reserva_detalle_venta_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='ubicacion_nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='abono',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_abono',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='detalle_venta_cantidad_producto',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='venta.venta', verbose_name='venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.CharField(default=1, max_length=45, verbose_name='nombre cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_mesa',
            field=models.IntegerField(default=2, verbose_name='numero de mesa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='fecha venta'),
        ),
    ]
