# Generated by Django 4.2.4 on 2023-10-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_detalle_venta_options_alter_ubicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre',
            new_name='ubicacion_nombre',
        ),
    ]
