# Generated by Django 4.2.4 on 2023-10-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_ubicacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='ubicacion_nombre',
            new_name='nombre',
        ),
    ]
