# Generated by Django 4.1.7 on 2023-04-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad Producto')),
                ('valor_total', models.FloatField(max_length=45, verbose_name='Valor Total venta')),
            ],
            options={
                'verbose_name_plural': 'detalle_ventas',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(help_text='MM/DD/AAAA', verbose_name='fecha venta')),
                ('detalle_venta_cantidad_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.detalle_venta', verbose_name='detalle venta cantidad producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Reserva')),
                ('hora_inicio', models.DateTimeField(help_text='HH/MM/SS', verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(help_text='HH/MM/SS', verbose_name='Hora de fin')),
                ('costo', models.FloatField()),
                ('abono', models.FloatField()),
                ('fecha_abono', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Abono')),
                ('pago_total', models.FloatField()),
                ('fecha_pago_total', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Pago Total')),
                ('detalle_venta_cantidad_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.detalle_venta', verbose_name='detalle venta cantidad producto')),
                ('ubicacion_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.ubicacion', verbose_name='ubicación nombre')),
            ],
        ),
    ]
