# Generated by Django 4.1.7 on 2023-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Reserva')),
                ('hora_inicio', models.DateTimeField(help_text='HH/MM/SS', verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(help_text='HH/MM/SS', verbose_name='Hora de fin')),
                ('costo', models.FloatField()),
                ('abono', models.FloatField()),
                ('fecha_abono', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Abono')),
                ('pago_total', models.FloatField()),
                ('fecha_pago_total', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Pago Total')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(help_text='MM/DD/AAAA', verbose_name='fecha venta')),
            ],
        ),
    ]
