# Generated by Django 4.1.7 on 2023-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=45, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=45, verbose_name='Producto')),
                ('descripcionProducto', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('precioProducto', models.FloatField(max_length=45, verbose_name='Precio')),
                ('ofertaProducto', models.IntegerField(max_length=45, verbose_name='Oferta')),
                ('stockProducto', models.IntegerField(max_length=45, verbose_name='Stock')),
            ],
        ),
    ]
