# Generated by Django 4.2 on 2023-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nombreMarca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcionProducto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='ofertaProducto',
            new_name='oferta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stockProducto',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default=1, max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
