# Generated by Django 4.2 on 2023-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_nombremarca_marca_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentotrabajador', models.IntegerField(max_length=45, verbose_name='Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=45, verbose_name='Presentacion')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadmedida', models.CharField(max_length=45, verbose_name='Medida')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
