# Generated by Django 4.2 on 2023-04-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_consumotrabajador_presentacion_unidadmedida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='marca',
            new_name='nombre',
        ),
    ]
