# Generated by Django 4.2 on 2023-04-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_marca_marca_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumoTrabajador',
            new_name='Consumo_trabajador',
        ),
        migrations.RenameModel(
            old_name='UnidadMedida',
            new_name='Unidad_medida',
        ),
    ]
