# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_trabajador_options_delete_trabajador_turno'),
        ('inventario', '0005_alter_marca_estado_alter_presentacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumotrabajador',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.trabajador', verbose_name='Trabajador'),
            preserve_default=False,
        ),
    ]
